# Generated by Django 3.2.5 on 2021-07-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190504_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dni',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'common user'), (2, 'premium user')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
